function [likely_param, range] = boot_strap(data_set, param_method, p_name)
%Uses function given by param_method to give bootstrap of parameter on data
%   Confidence interval given as [5%,95%]

%Set number of trials, indexing object L, and initialze params
B = 10000;
L = round(1+(length(data_set)-1)*rand(B,length(data_set)));
params = zeros(B,1);

%Generate L from data, and params from L
for i = 1:B
    L(i,:) = data_set(L(i,:));
    params(i) = param_method(L(i,:));
end

%Make pdf
x = linspace(min(params),max(params),1000);
epdf_object = empirical_pdf_object(params);
epdf = pdf(epdf_object,x);

%Determine most likely correct parameter and range
likely_param = x(epdf == max(epdf));
vars = VaR(params, epdf_object);
range = [vars(5),vars(95)]; %this represents a 90% confidence interval

%Plot
figure()
plot(x,epdf)
vline3(vars(5),'b','5% confidence level');
vline3(vars(95),'b','95% confidence level');
legend({['empirical pdf of ', p_name]},'location','NorthEast')
title(['PDF generated by bootstrapping ',p_name,' 10000 times'])
xlabel(p_name)
ylabel('probability density')

end

%[a,b] = boot_strap(data_set,square,'mean square');
